language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - mberneti@live.com
    on_success: always
    on_failure: always
node_js:
  - '9'
git:
  depth: 3
script:
  - npm install
  - npm build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: development
